import sqlite3
from fastapi import APIRouter, HTTPException, Query
from pathlib import Path


router = APIRouter(prefix="/api")


# ---------------------------------------------------------
# DATABASE PATH
# ---------------------------------------------------------

PROJECT_ROOT = Path(__file__).resolve().parents[3]
DB_PATH = PROJECT_ROOT / "backend" / "space_debris.db"


def get_connection():
    return sqlite3.connect(DB_PATH)


# ---------------------------------------------------------
# HEALTH
# ---------------------------------------------------------

@router.get("/health")
def health_check():
    return {
        "status": "ok"
    }


# ---------------------------------------------------------
# DASHBOARD SUMMARY
# ---------------------------------------------------------

@router.get("/dashboard")
def dashboard_summary():

    conn = get_connection()
    cursor = conn.cursor()

    cursor.execute("SELECT COUNT(*) FROM satellites")
    satellite_count = cursor.fetchone()[0]

    cursor.execute("SELECT COUNT(*) FROM conjunctions")
    conjunction_count = cursor.fetchone()[0]

    cursor.execute(
        "SELECT COUNT(*) FROM conjunctions WHERE severity = 'CRITICAL'"
    )
    critical_count = cursor.fetchone()[0]

    cursor.execute(
        "SELECT COUNT(*) FROM conjunctions WHERE severity = 'HIGH'"
    )
    high_count = cursor.fetchone()[0]

    cursor.execute(
        "SELECT COUNT(*) FROM conjunctions WHERE severity = 'MEDIUM'"
    )
    medium_count = cursor.fetchone()[0]

    cursor.execute(
        "SELECT COUNT(*) FROM conjunctions WHERE severity = 'LOW'"
    )
    low_count = cursor.fetchone()[0]

    conn.close()

    return {
        "satellite_count": satellite_count,
        "conjunction_count": conjunction_count,
        "severity_counts": {
            "critical": critical_count,
            "high": high_count,
            "medium": medium_count,
            "low": low_count
        }
    }


# ---------------------------------------------------------
# SATELLITES — LIST
# ---------------------------------------------------------

@router.get("/satellites")
def get_satellites(
    limit: int = Query(default=100, ge=1, le=500),
    offset: int = Query(default=0, ge=0)
):

    conn = get_connection()
    conn.row_factory = sqlite3.Row
    cursor = conn.cursor()

    cursor.execute(
        """
        SELECT
            norad_cat_id,
            object_name,
            epoch_utc,
            inclination,
            eccentricity,
            mean_motion
        FROM satellites
        ORDER BY norad_cat_id
        LIMIT ? OFFSET ?
        """,
        (limit, offset)
    )

    rows = cursor.fetchall()

    conn.close()

    return {
        "count": len(rows),
        "satellites": [dict(row) for row in rows]
    }


# ---------------------------------------------------------
# SATELLITES — DETAIL
# ---------------------------------------------------------

@router.get("/satellites/{norad_cat_id}")
def get_satellite(norad_cat_id: int):

    conn = get_connection()
    conn.row_factory = sqlite3.Row
    cursor = conn.cursor()

    cursor.execute(
        """
        SELECT *
        FROM satellites
        WHERE norad_cat_id = ?
        """,
        (norad_cat_id,)
    )

    row = cursor.fetchone()

    conn.close()

    if row is None:
        raise HTTPException(
            status_code=404,
            detail="Satellite not found"
        )

    return dict(row)


# ---------------------------------------------------------
# SATELLITES — TRAJECTORY
# ---------------------------------------------------------

@router.get("/satellites/{norad_cat_id}/trajectory")
def get_satellite_trajectory(norad_cat_id: int):

    # Trajectory data is currently generated by the
    # propagation/orchestration pipeline rather than stored
    # permanently in the satellites table.

    conn = get_connection()
    cursor = conn.cursor()

    cursor.execute(
        """
        SELECT norad_cat_id
        FROM satellites
        WHERE norad_cat_id = ?
        """,
        (norad_cat_id,)
    )

    row = cursor.fetchone()

    conn.close()

    if row is None:
        raise HTTPException(
            status_code=404,
            detail="Satellite not found"
        )

    return {
        "norad_cat_id": norad_cat_id,
        "trajectory": []
    }


# ---------------------------------------------------------
# CONJUNCTIONS — LIST
# ---------------------------------------------------------

@router.get("/conjunctions")
def get_conjunctions(
    severity: str | None = Query(default=None),
    limit: int = Query(default=100, ge=1, le=500),
    offset: int = Query(default=0, ge=0)
):

    conn = get_connection()
    conn.row_factory = sqlite3.Row
    cursor = conn.cursor()

    if severity is not None:

        severity = severity.upper()

        cursor.execute(
            """
            SELECT *
            FROM conjunctions
            WHERE severity = ?
            ORDER BY risk_score DESC
            LIMIT ? OFFSET ?
            """,
            (severity, limit, offset)
        )

    else:

        cursor.execute(
            """
            SELECT *
            FROM conjunctions
            ORDER BY risk_score DESC
            LIMIT ? OFFSET ?
            """,
            (limit, offset)
        )

    rows = cursor.fetchall()

    conn.close()

    return {
        "count": len(rows),
        "conjunctions": [dict(row) for row in rows]
    }


# ---------------------------------------------------------
# CONJUNCTIONS — DETAIL
# ---------------------------------------------------------

@router.get("/conjunctions/{conjunction_id}")
def get_conjunction(conjunction_id: int):

    conn = get_connection()
    conn.row_factory = sqlite3.Row
    cursor = conn.cursor()

    cursor.execute(
        """
        SELECT *
        FROM conjunctions
        WHERE id = ?
        """,
        (conjunction_id,)
    )

    row = cursor.fetchone()

    conn.close()

    if row is None:
        raise HTTPException(
            status_code=404,
            detail="Conjunction not found"
        )

    return dict(row)


# ---------------------------------------------------------
# CONJUNCTIONS — TRAJECTORY
# ---------------------------------------------------------

@router.get("/conjunctions/{conjunction_id}/trajectory")
def get_conjunction_trajectory(conjunction_id: int):

    conn = get_connection()
    cursor = conn.cursor()

    cursor.execute(
        """
        SELECT id
        FROM conjunctions
        WHERE id = ?
        """,
        (conjunction_id,)
    )

    row = cursor.fetchone()

    conn.close()

    if row is None:
        raise HTTPException(
            status_code=404,
            detail="Conjunction not found"
        )

    return {
        "conjunction_id": conjunction_id,
        "trajectory_a": [],
        "trajectory_b": []
    }